#include "auxiliary_functions.h"
//#include "table_.h"
#include "prepare_statement.h"
#include "execute_statement.h"
#include "meta_statement.h"

int main(void){
  while(true){
    InputBuffer* input_buffer = new_input_buffer();
    print_prompt();
    read_input(input_buffer);

    // Its a meta command if it starts with a dot(.)
    if(input_buffer->buffer[0]=='.'){
      switch(do_meta_command(input_buffer)){
      case (META_COMMAND_SUCCESS):
        printf("Meta command '%s' executed successfully.\n",input_buffer->buffer);
        continue;
      case META_COMMAND_UNRECOGNIZED_COMMAND:
        printf("Unrecognized meta command '%s'\n",input_buffer->buffer);
        continue;
      }
    }else{
      // Prepare bytecode from the given command
      Statement statement;
      switch(prepare_statement(input_buffer, &statement)){
      case PREPARE_SUCCESS:
        printf("Successfully generated bytecode for command '%s'\n",input_buffer->buffer);
        break;
      case PREPARE_UNRECOGNIZED_STATEMENT:
        printf("Failed to convert to bytecode, Unrecognized command '%s'\n",input_buffer->buffer);
        continue;
      }

      // Now execute the bytecode.
      execute_statement(&statement);
    }
  }
  return 0;
}
